// demo/landing.vue
<template>
	<!-- Language Selector -->
	<div class="language-selector">
		<select v-model="locale" class="language-dropdown">
			<option v-for="lang in availableLanguages" :key="lang" :value="lang" v-html="lang.toUpperCase()" />
		</select>
	</div>

	<!-- Wrapper -->
	<div id="wrapper">
		<!-- Intro -->
		<section class="intro">
			<header>
				<img class="logo" src="https://teknasyon.com/content/assets/img/logo/teknasyon-logo-white.svg" alt="" />
				<!-- ALREADY TRANSLATED -->
				<div>{{ $t('intro.title') }}</div>
				<h1>Yerel</h1>
				<p>
					We are a team that thinks big and has big goals. We start each new day with the aim of moving
					ourselves one step forward.
				</p>
				<ul class="actions">
					<li>
						<a href="#first" class="arrow scrolly"><span class="label">Next</span></a>
					</li>
				</ul>
			</header>
			<div class="content">
				<span class="image fill" data-position="center"><img
						src="https://teknasyon.com/content/uploads/pitstop-2024-flatten-1-min-scaled.jpg"
						alt="" /></span>
			</div>
		</section>

		<!-- Section -->
		<section id="first">
			<header>
				<h2>What Do We Do?</h2>
			</header>
			<div class="content">
				<p>
					Discover Teknasyon's focus! We develop mobile applications that touch lives and provide solutions to
					needs with strong stories. We are a strategic business partner that enables brands to grow on a
					global scale. Be a part of this story and discover Teknasyon for ventures.
				</p>
			</div>
		</section>

		<!-- Section -->
		<section>
			<header>
				<h2>Our Services</h2>
			</header>
			<div class="content">
				<p>
					As Teknasyon, we offer a wide range of services. We aim for excellence in every project.
				</p>

				<!-- Section -->
				<section>
					<header>
						<h3>B2C</h3>
						<p>
							We develop mobile applications that touch lives. By prioritizing user experience, we produce
							solutions that make life easier for millions of people.
						</p>
					</header>
					<div class="content">
						<div class="gallery">
							<a href="images/gallery/fulls/01.jpg" class="landscape"><img
									src="https://teknasyon.com/content/uploads/btb-7-n-1.png" alt="BTB 7 N 1" /></a>
							<a href="images/gallery/fulls/02.jpg"><img
									src="https://teknasyon.com/content/uploads/esim-gorsel-1.png" alt="E-Sim" /></a>
							<a href="images/gallery/fulls/03.jpg"><img
									src="https://teknasyon.com/content/uploads/lisa-gorsel-1.png" alt="Lisa" /></a>
							<a href="images/gallery/fulls/04.jpg" class="landscape"><img
									src="https://teknasyon.com/content/uploads/gtc-gorsel.png" alt="GTC" /></a>
						</div>
					</div>
				</section>

				<!-- Section -->
				<section>
					<header>
						<h3>B2B</h3>
						<p>
							We provide solutions to needs with strong stories. We develop projects that strengthen the
							technological infrastructure of businesses by supporting them in their digital
							transformation processes.
						</p>
					</header>
					<div class="content">
						<div class="gallery">
							<a href="images/gallery/fulls/05.jpg" class="landscape"><img
									src="https://teknasyon.com/content/uploads/rockads-laptop.png" alt="Rockads Laptop" /></a>
							<a href="images/gallery/fulls/06.jpg" class="landscape"><img
									src="https://teknasyon.com/content/uploads/desk-1.png" alt="Desk 1" /></a>
							<a href="images/gallery/fulls/07.jpg" class="landscape"><img
									src="https://teknasyon.com/content/uploads/zotlo2x.png" alt="Zotlo 2X" /></a>
						</div>
					</div>
				</section>

			</div>
		</section>
		<section>
			<header>
				<h2>Contact Us</h2>
			</header>
			<div class="content">
				<p>
					As the Teknasyon family, we are happy to communicate with you. Contact us for your projects,
					questions, or collaboration offers.
				</p>
				<form>
					<div class="fields">
						<div class="field half">
							<input type="text" name="name" id="name" placeholder="Name" />
						</div>
						<div class="field half">
							<input type="email" name="email" id="email" placeholder="Email" />
						</div>
						<div class="field">
							<textarea name="message" id="message" placeholder="Your Message" rows="7"></textarea>
						</div>
					</div>
					<ul class="actions">
						<li>
							<input type="submit" value="Send Message" class="button primary" />
						</li>
					</ul>
				</form>
			</div>
			<footer>
				<ul class="items">
					<li>
						<h3>Phone</h3>
						<a href="#">+90 212 963 15 50</a>
					</li>
					<li>
						<h3>Address</h3>
						<span>Büyükdere Cd. Uso Center Plaza No:245 Floor:7 Maslak - Istanbul</span>
					</li>
				</ul>
			</footer>
		</section>
	</div>

</template>
<script lang="ts" setup>
import { watch } from 'vue';
import { useI18n } from 'vue-i18n';

const { locale, availableLocales, t } = useI18n();
const availableLanguages = availableLocales;

const userMessage = 'Hello World!';
const userMessageAR = 'مرحبا بالعالم!';
const userMessageJP = 'こんにちは世界!';
const userMessageHB = 'שלום עולם!';
const userMessageKR = '안녕하세요 세계!';

const messages = {
  // İngilizce
  english: "Hello world, welcome to our application",
  
  // Türkçe
  turkish: "Merhaba dünya, uygulamamıza hoş geldiniz",
  
  // Arapça
  arabic: "مرحبا بكم في تطبيقنا",

	hebrew: "שלום עולם",

  // Çince (Basitleştirilmiş)
  chinese: "欢迎使用我们的应用程序",
  
  // Japonca
  japanese: "私たちのアプリケーションへようこそ",
  
  // Rusça
  russian: "Добро пожаловать в наше приложение",
  
  // Hintçe (Devanagari)
  hindi: "हमारे एप्लिकेशन में आपका स्वागत है",
  
  // İspanyolca
  spanish: "Bienvenido a nuestra aplicación",
  
  // Fransızca
  french: "Bienvenue dans notre application",
  
  // Technical strings (filtrelenmeli)
  apiUrl: "https://api.example.com/users",
  className: "btn-primary",
  functionName: "handleUserClick",
  
  // Kod benzeri (filtrelenmeli)
  constant: "API_KEY_123",
  short: "OK"
};

const translationPattern = /(?:\$t\(|\.t\(|i18n\.t\()\s*["'`]([^"'`]+)["'`]/g;

const messageFromTranslate = t('hello.moto');

console.log('User Message:', messages, userMessage, userMessageAR, userMessageJP, userMessageHB, userMessageKR, messageFromTranslate);

const templateLiteralText = `
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Vivamus lacinia odio vitae vestibulum.
`;

function sayHello(page: string, param2: string) {
	console.log(page, 'Hello!!!', param2);
	return page;
}

const attrName = 'data-i18n';

const attrPattern = new RegExp(
	`\\b${attrName}\\s*=\\s*["']([^"']+)["']`,
	'gi'
);

const attrPattern2 = new RegExp(`\\b${attrName}\\s*=\\s*["']([^"']+)["']`, 'gi');

sayHello('Home page', 'Second param');

watch(locale, (newLocale) => {
	console.log('Locale changed to:', newLocale);
});
</script>

<style scoped>
.language-selector {
	position: fixed;
	top: 20px;
	right: 20px;
	z-index: 1000;
}

.language-dropdown {
	background: rgba(255, 255, 255, 0.95);
	border: 1px solid rgba(0, 123, 255, 0.2);
	border-radius: 8px;
	padding: 8px 12px;
	font-size: 14px;
	font-weight: 500;
	color: #2c3e50;
	cursor: pointer;
	backdrop-filter: blur(10px);
	transition: all 0.3s ease;
	box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
	min-width: 60px;
	text-align: center;
}

.language-dropdown:hover {
	border-color: #007bff;
	box-shadow: 0 4px 20px rgba(0, 123, 255, 0.2);
	transform: translateY(-1px);
}

.language-dropdown:focus {
	outline: none;
	border-color: #007bff;
	box-shadow: 0 0 0 3px rgba(0, 123, 255, 0.1);
}

.language-dropdown option {
	background: white;
	color: #2c3e50;
	padding: 8px;
}
</style>

// demo/landing.jsx
import React, { useEffect, useState } from 'react';
import { useTranslation } from 'react-i18next';

const App = () => {
  const { i18n } = useTranslation();
  const [locale, setLocale] = useState(i18n.language);
  const availableLanguages = ['en', 'tr']; // Add your available languages here

  const userMessage = 'Hello World!';
  const userMessageAR = 'مرحبا بالعالم!';
  const userMessageJP = 'こんにちは世界!';
  const userMessageHB = 'שלום עולם!';
  const userMessageKR = '안녕하세요 세계!';

  const messages = {
    // İngilizce
    english: "Hello world, welcome to our application",
    
    // Türkçe
    turkish: "Merhaba dünya, uygulamamıza hoş geldiniz",
    
    // Arapça
    arabic: "مرحبا بكم في تطبيقنا",

    hebrew: "שלום עולם",

    // Çince (Basitleştirilmiş)
    chinese: "欢迎使用我们的应用程序",
    
    // Japonca
    japanese: "私たちのアプリケーションへようこそ",
    
    // Rusça
    russian: "Добро пожаловать в наше приложение",
    
    // Hintçe (Devanagari)
    hindi: "हमारे एप्लिकेशन में आपका स्वागत है",
    
    // İspanyolca
    spanish: "Bienvenido a nuestra aplicación",
    
    // Fransızca
    french: "Bienvenue dans notre application",
    
    // Technical strings (filtrelenmeli)
    apiUrl: "https://api.example.com/users",
    className: "btn-primary",
    functionName: "handleUserClick",
    
    // Kod benzeri (filtrelenmeli)
    constant: "API_KEY_123",
    short: "OK"
  };

  const translationPattern = /(?:\$t\(|\.t\(|i18n\.t\()\s*["'`]([^"'`]+)["'`]/g;

  console.log('User Message:', messages, userMessage, userMessageAR, userMessageJP, userMessageHB, userMessageKR);
  
  useEffect(() => {
    const handleLanguageChange = () => {
      console.log('Locale changed to:', locale);
    };
    handleLanguageChange();
  }, [locale]);

  const handleLanguageChange = (e) => {
    const newLocale = e.target.value;
    setLocale(newLocale);
    i18n.changeLanguage(newLocale);
  };

  const templateLiteralText = `
  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
  Vivamus lacinia odio vitae vestibulum.
  `;

  function sayHello(page, param2) {
    console.log(page, 'Hello!!!', param2);
    return page;
  }

  sayHello('Home page', 'Second param');

  const attrName = 'data-i18n';

  const attrPattern = new RegExp(
    `\\b${attrName}\\s*=\\s*["']([^"']+)["']`,
    'gi'
  );

  const attrPattern2 = new RegExp(`\\b${attrName}\\s*=\\s*["']([^"']+)["']`, 'gi');

  return (
    <>
      <div className="language-selector">
        <select value={locale} onChange={handleLanguageChange} className="language-dropdown">
          {availableLanguages.map((lang) => (
            <option key={lang} value={lang}>
              {lang.toUpperCase()}
            </option>
          ))}
        </select>
      </div>

      <div id="wrapper">
        <section className="intro">
          <header>
            <img className="logo" src="https://teknasyon.com/content/assets/img/logo/teknasyon-logo-white.svg" alt="" />
            <h1>Yerel</h1>
            <p>
              We are a team that thinks big and has big goals. We start each new day with the aim of moving
              ourselves one step forward.
            </p>
            <ul className="actions">
              <li>
                <a href="#first" className="arrow scrolly"><span className="label">Next</span></a>
              </li>
            </ul>
          </header>
          <div className="content">
            <span className="image fill" data-position="center">
              <img src="https://teknasyon.com/content/uploads/pitstop-2024-flatten-1-min-scaled.jpg" alt="" />
            </span>
          </div>
        </section>

        <section id="first">
          <header>
            <h2>What Do We Do?</h2>
          </header>
          <div className="content">
            <p>
              Discover Teknasyon's focus! We develop mobile applications that touch lives and provide solutions to
              needs with strong stories. We are a strategic business partner that enables brands to grow on a
              global scale. Be a part of this story and discover Teknasyon for ventures.
            </p>
          </div>
        </section>

        <section>
          <header>
            <h2>Our Services</h2>
          </header>
          <div className="content">
            <p>
              As Teknasyon, we offer a wide range of services. We aim for excellence in every project.
            </p>

            <section>
              <header>
                <h3>B2C</h3>
                <p>
                  We develop mobile applications that touch lives. By prioritizing user experience, we produce
                  solutions that make life easier for millions of people.
                </p>
              </header>
              <div className="content">
                <div className="gallery">
                  <a href="images/gallery/fulls/01.jpg" className="landscape">
                    <img src="https://teknasyon.com/content/uploads/btb-7-n-1.png" alt="BTB 7 N 1" />
                  </a>
                  <a href="images/gallery/fulls/02.jpg">
                    <img src="https://teknasyon.com/content/uploads/esim-gorsel-1.png" alt="E-Sim Alt text" />
                  </a>
                  <a href="images/gallery/fulls/03.jpg">
                    <img src="https://teknasyon.com/content/uploads/lisa-gorsel-1.png" alt="Lisa Alt text" />
                  </a>
                  <a href="images/gallery/fulls/04.jpg" className="landscape">
                    <img src="https://teknasyon.com/content/uploads/gtc-gorsel.png" alt="GTC Alt text" />
                  </a>
                </div>
              </div>
            </section>

            <section>
              <header>
                <h3>B2B</h3>
                <p>
                  We provide solutions to needs with strong stories. We develop projects that strengthen the
                  technological infrastructure of businesses by supporting them in their digital
                  transformation processes.
                </p>
              </header>
              <div className="content">
                <div className="gallery">
                  <a href="images/gallery/fulls/05.jpg" className="landscape">
                    <img src="https://teknasyon.com/content/uploads/rockads-laptop.png" alt="Rockads Laptop" />
                  </a>
                  <a href="images/gallery/fulls/06.jpg" className="landscape">
                    <img src="https://teknasyon.com/content/uploads/desk-1.png" alt="Desk 1" />
                  </a>
                  <a href="images/gallery/fulls/07.jpg" className="landscape">
                    <img src="https://teknasyon.com/content/uploads/zotlo2x.png" alt="Zotlo 2X" />
                  </a>
                </div>
              </div>
            </section>

          </div>
        </section>
        <section>
          <header>
            <h2>Contact Us</h2>
          </header>
          <div className="content">
            <p>
              As the Teknasyon family, we are happy to communicate with you. Contact us for your projects,
              questions, or collaboration offers.
            </p>
            <form>
              <div className="fields">
                <div className="field half">
                  <input type="text" name="name" id="name" placeholder="Name" />
                </div>
                <div className="field half">
                  <input type="email" name="email" id="email" placeholder="Email" />
                </div>
                <div className="field">
                  <textarea name="message" id="message" placeholder="Your Message" rows="7"></textarea>
                </div>
              </div>
              <ul className="actions">
                <li>
                  <input type="submit" value="Send Message" className="button primary" />
                </li>
              </ul>
            </form>
          </div>
          <footer>
            <ul className="items">
              <li>
                <h3>Phone</h3>
                <a href="#">+90 212 963 15 50</a>
              </li>
              <li>
                <h3>Address</h3>
                <span>Büyükdere Cd. Uso Center Plaza No:245 Floor:7 Maslak - Istanbul</span>
              </li>
            </ul>
          </footer>
        </section>
      </div>
    </>
  );
};

export default App;
